### ISSUE TITLE
STYLING/ TO-DO

### ISSUE THREAD

**Issue by yarelismartin** [yarelismartin/Rare-FE#32]
- [ ] Add images to the post that contain images 
- [ ] Add images to every profile user 
- [ ] Create more post data 
- [x] post card date format 
- [ ] filter comment button (newest-oldest)
